# CMake generated Testfile for 
# Source directory: D:/Final Project/arx-platform-v2.0/arx-platform
# Build directory: D:/Final Project/arx-platform-v2.0/arx-platform/build_qt
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[arx_test_filters]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/Debug/arx_test_filters.exe")
  set_tests_properties([=[arx_test_filters]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;151;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[arx_test_filters]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/Release/arx_test_filters.exe")
  set_tests_properties([=[arx_test_filters]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;151;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[arx_test_filters]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/MinSizeRel/arx_test_filters.exe")
  set_tests_properties([=[arx_test_filters]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;151;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[arx_test_filters]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/RelWithDebInfo/arx_test_filters.exe")
  set_tests_properties([=[arx_test_filters]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;151;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
else()
  add_test([=[arx_test_filters]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[arx_test_gestures]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/Debug/arx_test_gestures.exe")
  set_tests_properties([=[arx_test_gestures]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;155;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[arx_test_gestures]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/Release/arx_test_gestures.exe")
  set_tests_properties([=[arx_test_gestures]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;155;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[arx_test_gestures]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/MinSizeRel/arx_test_gestures.exe")
  set_tests_properties([=[arx_test_gestures]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;155;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[arx_test_gestures]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/RelWithDebInfo/arx_test_gestures.exe")
  set_tests_properties([=[arx_test_gestures]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;155;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
else()
  add_test([=[arx_test_gestures]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[arx_test_replay]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/Debug/arx_test_replay.exe")
  set_tests_properties([=[arx_test_replay]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;159;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[arx_test_replay]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/Release/arx_test_replay.exe")
  set_tests_properties([=[arx_test_replay]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;159;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[arx_test_replay]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/MinSizeRel/arx_test_replay.exe")
  set_tests_properties([=[arx_test_replay]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;159;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[arx_test_replay]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/RelWithDebInfo/arx_test_replay.exe")
  set_tests_properties([=[arx_test_replay]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;159;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
else()
  add_test([=[arx_test_replay]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[arx_test_runtime]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/Debug/arx_test_runtime.exe")
  set_tests_properties([=[arx_test_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;163;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[arx_test_runtime]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/Release/arx_test_runtime.exe")
  set_tests_properties([=[arx_test_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;163;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[arx_test_runtime]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/MinSizeRel/arx_test_runtime.exe")
  set_tests_properties([=[arx_test_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;163;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[arx_test_runtime]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/RelWithDebInfo/arx_test_runtime.exe")
  set_tests_properties([=[arx_test_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;163;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
else()
  add_test([=[arx_test_runtime]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[arx_test_transport]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/Debug/arx_test_transport.exe")
  set_tests_properties([=[arx_test_transport]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;167;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[arx_test_transport]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/Release/arx_test_transport.exe")
  set_tests_properties([=[arx_test_transport]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;167;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[arx_test_transport]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/MinSizeRel/arx_test_transport.exe")
  set_tests_properties([=[arx_test_transport]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;167;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[arx_test_transport]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/RelWithDebInfo/arx_test_transport.exe")
  set_tests_properties([=[arx_test_transport]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;167;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
else()
  add_test([=[arx_test_transport]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[arx_test_cli]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/Debug/arx_test_cli.exe")
  set_tests_properties([=[arx_test_cli]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;171;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[arx_test_cli]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/Release/arx_test_cli.exe")
  set_tests_properties([=[arx_test_cli]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;171;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[arx_test_cli]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/MinSizeRel/arx_test_cli.exe")
  set_tests_properties([=[arx_test_cli]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;171;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[arx_test_cli]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/RelWithDebInfo/arx_test_cli.exe")
  set_tests_properties([=[arx_test_cli]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;171;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
else()
  add_test([=[arx_test_cli]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[arx_test_tracking_setup]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/Debug/arx_test_tracking_setup.exe")
  set_tests_properties([=[arx_test_tracking_setup]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;175;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[arx_test_tracking_setup]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/Release/arx_test_tracking_setup.exe")
  set_tests_properties([=[arx_test_tracking_setup]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;175;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[arx_test_tracking_setup]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/MinSizeRel/arx_test_tracking_setup.exe")
  set_tests_properties([=[arx_test_tracking_setup]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;175;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[arx_test_tracking_setup]=] "D:/Final Project/arx-platform-v2.0/arx-platform/build_qt/RelWithDebInfo/arx_test_tracking_setup.exe")
  set_tests_properties([=[arx_test_tracking_setup]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;175;add_test;D:/Final Project/arx-platform-v2.0/arx-platform/CMakeLists.txt;0;")
else()
  add_test([=[arx_test_tracking_setup]=] NOT_AVAILABLE)
endif()
